"""create financial_health_scores table

Revision ID: 9fddf8512d9f
Revises: f31a02ab1abf
Create Date: 2026-07-12 14:05:48.591926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fddf8512d9f'
down_revision: Union[str, None] = 'f31a02ab1abf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_health_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('liquidity_score', sa.Float(), nullable=True),
    sa.Column('solvency_score', sa.Float(), nullable=True),
    sa.Column('profitability_score', sa.Float(), nullable=True),
    sa.Column('leverage_score', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_health_scores_id'), 'financial_health_scores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_health_scores_id'), table_name='financial_health_scores')
    op.drop_table('financial_health_scores')
    # ### end Alembic commands ###
